DROP DATABASE IF EXISTS fyve;

CREATE DATABASE fyve;

USE fyve;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
   id INT NOT NULL AUTO_INCREMENT,
   fname VARCHAR(128) NOT NULL,
   lname VARCHAR(128) NOT NULL,
   email VARCHAR(128) NOT NULL,
   username VARCHAR(128) NOT NULL,
   password VARCHAR(128) NOT NULL,
   register_date DATE NOT NULL,
   PRIMARY KEY  (`id`)
);

